create sequence country_id_seq increment by 50;
create sequence group_standing_id_seq increment by 50;
create sequence message_id_seq increment by 50;
create sequence photo_id_seq increment by 50;
create sequence playoff_game_id_seq increment by 50;
create sequence replay_id_seq increment by 50;
create sequence schedule_seq increment by 50;

alter sequence bet_seq rename to bet_id_seq;
alter sequence application_seq rename to application_id_seq;
alter sequence comment_seq rename to comment_id_seq;
alter sequence game_seq rename to game_id_seq;
alter sequence group_seq rename to group_id_seq;
alter sequence rating_seq rename to rating_id_seq;
alter sequence schedule_seq rename to schedule_id_seq;
alter sequence tournament_seq rename to tournament_id_seq;
alter sequence user_seq rename to user_id_seq;

alter sequence application_id_seq increment by 50;
alter sequence bet_id_seq increment by 50;
alter sequence comment_id_seq increment by 50;
alter sequence country_id_seq increment by 50;
alter sequence game_id_seq increment by 50;
alter sequence group_id_seq increment by 50;
alter sequence group_standing_id_seq increment by 50;
alter sequence message_id_seq increment by 50;
alter sequence photo_id_seq increment by 50;
alter sequence playoff_game_id_seq increment by 50;
alter sequence rating_id_seq increment by 50;
alter sequence replay_id_seq increment by 50;
alter sequence schedule_id_seq increment by 50;
alter sequence tournament_id_seq increment by 50;
alter sequence user_id_seq increment by 50;

alter table application alter column id set default nextval('application_id_seq');
alter table bet alter column id set default nextval('bet_id_seq');
alter table comment alter column id set default nextval('comment_id_seq');
alter table country alter column id set default nextval('country_id_seq');
alter table game alter column id set default nextval('game_id_seq');
alter table "group" alter column id set default nextval('group_id_seq');
alter table group_standing alter column id set default nextval('group_standing_id_seq');
alter table message alter column id set default nextval('message_id_seq');
alter table photo alter column id set default nextval('photo_id_seq');
alter table playoff_game alter column id set default nextval('playoff_game_id_seq');
alter table rating alter column id set default nextval('rating_id_seq');
alter table replay alter column id set default nextval('replay_id_seq');
alter table schedule alter column id set default nextval('schedule_id_seq');
alter table tournament alter column id set default nextval('tournament_id_seq');
alter table "user" alter column id set default nextval('user_id_seq');
